import express from "express";
import authRoutes from "./auth/auth.route.js";
import adminRoutes from "./admin/index.js";
import unitRoutes from "./units/unit.route.js";
import userRoutes from "./users/user.route.js";
import cycleRoutes from "./cycle/cycle.route.js";
import okrRoutes from "./okr/index.js";
import kpiRoutes from "./kpi/index.js";
import okrAiRoutes from "./okr-ai/okrAi.route.js";
import behaviorAiRoutes from "./behavior-ai/behaviorAi.route.js";
import aiUsageRoutes from "./ai-usage/ai-usage.route.js";
import healthRoutes from "./health/health.route.js";
import statisticRoutes from "./statistic/statistic.route.js";
import notificationRoutes from "./notifications/notification.route.js";
import companyRoutes from "./company/company.route.js";
const router = express.Router();

router.use("/health", healthRoutes);
router.use("/admin", adminRoutes);
router.use("/auth", authRoutes);
router.use("/units", unitRoutes);
router.use("/users", userRoutes);
router.use("/cycles", cycleRoutes);
router.use("/", okrRoutes);
router.use("/", kpiRoutes);
router.use("/", okrAiRoutes);
router.use("/behavior-ai", behaviorAiRoutes);
router.use("/ai-usage", aiUsageRoutes);
router.use("/statistics", statisticRoutes);
router.use("/notifications", notificationRoutes);
router.use("/company", companyRoutes);

export default router;
